// sutochno: find places to stay (hotels, apartments) in a city for given check-in and check-out dates, with the price for the stay
//
// Generated by `webtap map` (reviewed: price per stay, no-rating = undefined) on 2026-10-02 from https://sutochno.ru/. Review before committing:
// the request and parse function come from one recorded run of the site's frontend.
import { browser, defineSite, endpoint, type FetchJson, requests, z } from "../../src/index.js";

const Input = z.object({
  city: z.string().min(1),
  checkIn: z.string().min(1),
  checkOut: z.string().min(1),
  limit: z.number().int().min(1).max(50).default(10),
});
type Input = z.output<typeof Input>;

const Item = z.object({
  title: z.string(),
  priceRub: z.number().optional(),
  rating: z.number().optional(),
  address: z.string().optional(),
  url: z.string(),
  imageUrl: z.string().optional(),
});
type Item = z.output<typeof Item>;

// Recorded call chain (the site's own frontend):
//   #0 GET https://sutochno.ru/api/rest/search/getTermSuggestionsWithBoundingBox?query=Сочи
//   #1 GET https://sutochno.ru/api/json/search/searchObjectsOnMap?max_guests=2&currencyId=1&count=50&offset=0&NE[lat]=44.34055287459533&NE[lng]=40.31612498437501&SW[lat]=43.07946873236
//   #2 GET https://sutochno.ru/api/json/search/searchObjectsByLocation?ids[]=760857&ids[]=1357913&ids[]=1468265&ids[]=1008083&max_guests=2&relevance=pairs&currencyId=1&dateBegin=2026-1
// Wired by the mapper's LLM and run against the live site with the sample input (2026-10-02). Review it.
const runChain: (input: Input, fetchJson: FetchJson) => Promise<{ items?: unknown[] }> = async (input: any, fetchJson: any) => {
  const city = input.city;
  const checkIn = input.checkIn;
  const checkOut = input.checkOut;
  const limit = input.limit ?? 10;

  const apiHeaders = {
    accept: 'application/json, text/plain, */*',
    'api-version': '2.1',
    platform: 'js',
    token: 'Hy6U3z61fflbgT2yJ/VdlQ2719',
    referer: 'https://sutochno.ru/'
  };

  const suggestRes = await fetchJson({
    url: `https://sutochno.ru/api/rest/search/getTermSuggestionsWithBoundingBox?query=${encodeURIComponent(city)}`,
    headers: apiHeaders
  });
  const suggestion = suggestRes?.data?.suggestions?.[0];
  if (!suggestion) return { items: [] };

  const locationId = suggestion.location?.id;
  const locationType = suggestion.location?.type ?? 'city';
  const bbox = suggestion.bbox ?? {};
  const NE = bbox.NE ?? {};
  const SW = bbox.SW ?? {};

  const searchReferer = `https://sutochno.ru/front/searchapp/search?guests_adults=2&occupied=${encodeURIComponent(checkIn)};${encodeURIComponent(checkOut)}&term=${encodeURIComponent(city)}&id=${encodeURIComponent(locationId)}&type=${encodeURIComponent(locationType)}&SW.lat=${encodeURIComponent(SW.lat)}&SW.lng=${encodeURIComponent(SW.lng)}&NE.lat=${encodeURIComponent(NE.lat)}&NE.lng=${encodeURIComponent(NE.lng)}`;

  const mapRes = await fetchJson({
    url: `https://sutochno.ru/api/json/search/searchObjectsOnMap?max_guests=2&currencyId=1&count=50&offset=0&NE[lat]=${encodeURIComponent(NE.lat)}&NE[lng]=${encodeURIComponent(NE.lng)}&SW[lat]=${encodeURIComponent(SW.lat)}&SW[lng]=${encodeURIComponent(SW.lng)}&location_type=${encodeURIComponent(locationType)}&location_id=${encodeURIComponent(locationId)}&relevance=pairs&dateBegin=${encodeURIComponent(checkIn)}&dateEnd=${encodeURIComponent(checkOut)}`,
    headers: { ...apiHeaders, referer: searchReferer }
  });
  const objects = mapRes?.data?.objects ?? [];
  const ids = objects
    .slice(0, limit)
    .map((o: any) => o.id)
    .filter((id: any) => id !== undefined && id !== null);

  if (ids.length === 0) return { items: [] };

  const idsQuery = ids.map((id: any) => `ids[]=${encodeURIComponent(id)}`).join('&');
  const detailRes = await fetchJson({
    url: `https://sutochno.ru/api/json/search/searchObjectsByLocation?${idsQuery}&max_guests=2&relevance=pairs&currencyId=1&dateBegin=${encodeURIComponent(checkIn)}&dateEnd=${encodeURIComponent(checkOut)}`,
    headers: { ...apiHeaders, referer: searchReferer }
  });
  const details = detailRes?.data?.objects ?? [];

  const items = details
    .map((o: any) => {
      // Reviewed: the goal is the price for the whole stay (the mapper picked per night first).
      const priceVal = o.prices?.full?.value ?? o.prices?.perDay?.value;
      const ratingVal = o.rating?.value;
      const addr = o.location?.address;

      let address;
      if (addr) {
        const parts = [];
        if (addr.city?.title) parts.push(addr.city.title);

        const streetParts = [];
        if (addr.street?.title) streetParts.push(addr.street.title);
        if (addr.streetType?.title) streetParts.push(addr.streetType.title);
        let streetStr = streetParts.join(' ');
        if (addr.house) streetStr = streetStr ? `${streetStr}, ${addr.house}` : addr.house;
        if (streetStr) parts.push(streetStr);

        address = parts.length ? parts.join(', ') : undefined;
      }

      const imageUrl = o.media?.images?.[0]?.imageUrl;

      return {
        title: o.title,
        priceRub: typeof priceVal === 'number' ? priceVal : (priceVal !== undefined ? Number(priceVal) : undefined),
        rating: typeof ratingVal === 'number' && ratingVal > 0 ? Math.round(ratingVal * 10) / 10 : undefined, // reviewed: 0 = no reviews yet
        address,
        url: `https://sutochno.ru/objects/${o.id}`,
        imageUrl
      };
    })
    .filter((item: any) => item.title);

  return { items };
};
const run = async (i: Input, fetchJson: FetchJson) => ({ items: ((await runChain(i, fetchJson)).items ?? []).slice(0, i.limit) as Item[] });

export const sutochno = defineSite({
  id: "sutochno",
  origin: "https://sutochno.ru",
  rateLimit: { minIntervalMs: 2_000 },
  endpoints: {
    search: endpoint(
      { description: "find places to stay (hotels, apartments) in a city for given check-in and check-out dates, with the price for the stay", input: Input, output: z.object({ items: z.array(Item) }) },
      {
        strategies: [
          requests({ run }),
          requests({ via: "page", warmUrl: "/", run }),
          browser({
            run: async (s, i) => {
              await s.goto("https://sutochno.ru/");
              await s.act("type %city% into the \"Куда едем\" destination field", { cacheKey: "search.step1", variables: { city: String(i.city), checkIn: String(i.checkIn), checkOut: String(i.checkOut) } });
              await s.act("click the \"Сочи,Краснодарский край\" suggestion in the dropdown", { cacheKey: "search.step2", variables: { city: String(i.city), checkIn: String(i.checkIn), checkOut: String(i.checkOut) } });
              await s.act("click on the day \"16\" in the October 2026 calendar to set the check-in date", { cacheKey: "search.step3", variables: { city: String(i.city), checkIn: String(i.checkIn), checkOut: String(i.checkOut) } });
              await s.act("click on the day \"18\" in the October 2026 calendar to set the check-out date", { cacheKey: "search.step4", variables: { city: String(i.city), checkIn: String(i.checkIn), checkOut: String(i.checkOut) } });
              await s.act("click the Найти button to search", { cacheKey: "search.step5", variables: { city: String(i.city), checkIn: String(i.checkIn), checkOut: String(i.checkOut) } });
              const out = await s.extract("The result items shown on the page for: find places to stay (hotels, apartments) in a city for given check-in and check-out dates, with the price for the stay", z.object({ items: z.array(Item) }));
              return { items: out.items.slice(0, i.limit) };
            },
          }),
        ],
        canary: { input: {"city":"Сочи","checkIn":"2026-10-16","checkOut":"2026-10-18"} },
      },
    ),
  },
});
